name: CI Pipeline

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

permissions:
  contents: read
  packages: write

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Skip auth/pull for forked PRs to avoid failures with private images
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PICKEYCAR }}
      - name: Show actor
        run: echo "Actor is ${{ github.actor }}"
      - name: Check if GHCR_PAT is set
        run: |
          if [ -z "${{ secrets.PICKEYCAR }}" ]; then
            echo "PICKEYCAR is not set!"
            exit 1
          else
            echo "PICKEYCAR is set."
          fi

      - name: Pull CI image
        run: docker pull ghcr.io/ammaralh/pickeycar-ci:latest

      - uses: actions/checkout@v4
      - name: Build
        run: |
          source /opt/ros/jazzy/setup.bash
          colcon build --merge-install --cmake-args -DCMAKE_BUILD_TYPE=Coverage
